---
# tasks file for nginx
- name: Add Nginx Repository
  apt_repository:
    repo: ppa:nginx/stable
    state: present

- name: Install Nginx
  apt:
    pkg: nginx
    state: installed
    update_cache: true
  notify:
    - Start Nginx

- name: Disable Default Site Configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

# `dest` in quotes as a variable is used!
- name: Add SFH Site Config
  register: sfhconfig
  template:
    src: yourdomain.se.conf.j2
    dest: '/etc/nginx/sites-available/{{ domain }}.conf'
    owner: ubuntu
    group: ubuntu

# `src`/`dest` in quotes as a variable is used!
- name: Enable SFH Site Config
  file:
    src: '/etc/nginx/sites-available/{{ domain }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ domain }}.conf'
    state: link

# `src`/`dest` in quotes as a variable is used!
- name: Enable SFH Site Config
  file:
    src: '/etc/nginx/sites-available/{{ domain }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ domain }}.conf'
    state: link

# `dest` in quotes as a variable is used!
- name: Create Web ubuntu
  file:
    dest: '/var/www/{{ domain }}/public'
    mode: 775
    state: directory
    owner: ubuntu
    group: ubuntu
  notify:
    - Reload Nginx

# `dest` in quotes as a variable is used!
- name: Web ubuntu Permissions
  file:
   dest: '/var/www/{{ domain }}'
   mode: 775
   state: directory
   owner: ubuntu
   group: ubuntu
   recurse: yes
  notify:
    - Reload Nginx

# Copy index.html to server
- name: Copy website content
  copy:
    src: index.html
    dest: '/var/www/{{ domain }}/public'
    owner: ubuntu
    group: ubuntu
