---
- name: Deploy control machine
  os_server:
    state: present
    name: controlmachine
    image: Ubuntu server 16.04
    key_name: 2dv514-g2-key
    wait: yes
    flavor: cpu1-ram1024-disk10
    auto_floating_ip: yes
    network: Acme_LAN
    security_groups:
      - default
      - ssh
      - http
    meta:
      hostname: controlmachine.localdomain
  register: controlmachine

# - debug: msg="hostvars={{hostvars}}"

- name: Add VM to inventory
  add_host:
    name: controlmachine
    hostname: "{{controlmachine.server.public_v4}}"
    ansible_host: "{{controlmachine.server.public_v4}}"

- name: Wait for SSH to be ready
  pause:
    seconds: 60

# - debug: msg="hostvars={{hostvars}}"

# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     dest: ./hosts
#     line: "{{ hostvars['controlmachine'].ansible_host }} {{ hostvars['controlmachine'].inventory_hostname }} {{ hostvars['controlmachine'].inventory_hostname_short }}"
#     state: present
